name: Recover Keystore

on:
  workflow_dispatch:

jobs:
  recover-keystore:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Decode and Upload Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks
          echo "Keystore file created successfully"
          ls -la keystore.jks
          
      - name: Save keystore password to file
        run: |
          echo "${{ secrets.KEYSTORE_PASS }}" > keystore_password.txt
          echo "Password saved to keystore_password.txt"
          
      - name: Save local.properties if exists
        run: |
          if [ -n "${{ secrets.LOCAL_PROPERTIES }}" ]; then
            echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties
            echo "Local properties saved"
          else
            echo "No LOCAL_PROPERTIES secret found"
          fi
          
      - name: Upload all signing files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signing-files
          path: |
            keystore.jks
            keystore_password.txt
            local.properties
          retention-days: 1
          
      - name: Show keystore info
        run: |
          echo "Files created:"
          ls -la keystore.jks keystore_password.txt local.properties 2>/dev/null || true
          echo ""
          echo "You can use keytool to inspect the keystore:"
          echo "keytool -list -v -keystore keystore.jks"
