name: Recover Keystore

on:
  workflow_dispatch:

jobs:
  recover-keystore:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Decode and Upload Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks
          echo "Keystore file created successfully"
          ls -la keystore.jks
          
      - name: Upload keystore as artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore.jks
          retention-days: 1
          
      - name: Show keystore info
        run: |
          echo "Keystore password is stored in KEYSTORE_PASS secret"
          echo "You can use keytool to inspect the keystore:"
          echo "keytool -list -v -keystore keystore.jks"
